before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: l+d1C5c2s1ibUgoy1Gs576qYrbq90cvEde9aJ+P+J/dZ28J4equpnqXD4953iURsSR0e9oZPHAVKEitoOdUHr/hWiexbciQhS2q+YlJSunwRf2zmGb+6kTFkVEJzyBPxYNNLb7ealtzbiQNw3h0NgH8p4CYWNi+JGRvRof1muKWI4lXzH0OZI0gJsmW4y7/wBt5mNW9WBJTue/VBzLhUK0FqMTaXTpKRoJyEcFol2p2PlIux/qXfYvGxv6QfiQa7QwND1/KelOtYgSNlisM2AU3Zj1wb/MqY+MKAVawsy9+WimCW+NfwVsAFxxaMO084atMhSXWEBf8MfeE15HKdf4xroZsLaKfqrQAggSmC4dLl/wDf0kgvV2BqW/tAOztg9NN5IK6ytqrCceV92lAZ7EVsvAbue1FcsT5DANOThUTkJTHEgyMwkpsSr9F7vb/xfEyvKE7Plgglfg1laNFFYYpZheEDuOuLQGWx+Wrlfhjhndi7IzRHDnlDfQKArLhbYuA4Gh9QGBJf2fjNLuQ9UMkrDOu7gGer2/lTreFYWLQp1mqMGzWJ4+NMzIjoFYOf05TCAbyKrTVE+KKDlItYLgSRqh4vwZehAfBvywCQmgIb2k0dco4sU19dmYEStDbjwWyNWcVOKn3NkvsQCMlQG5iWS79l/R70lcnYyhbhfY4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
